// GENERATED by tools/encode-frames.mjs — do not edit by hand. Re-run the encoder instead.
export const FILM_GEN = {
  "version": 3,
  "count": 300,
  "padding": 3,
  "pattern": "f_%03d.webp",
  "ext": "webp",
  "watermarkPatch": {
    "cx": 1740,
    "cy": 900,
    "hole": 58,
    "ring": 78,
    "iterations": 220
  },
  "watermarkPatchPortrait": {
    "cx": 900,
    "cy": 1740,
    "hole": 58,
    "ring": 78,
    "iterations": 220
  },
  "tiers": [
    {
      "id": "xl",
      "orientation": "landscape",
      "dir": "/film/1920",
      "width": 1920,
      "height": 1080,
      "totalBytes": 13554298,
      "avgBytes": 45181
    },
    {
      "id": "lg",
      "orientation": "landscape",
      "dir": "/film/1280",
      "width": 1280,
      "height": 720,
      "totalBytes": 8894882,
      "avgBytes": 29650
    },
    {
      "id": "sm",
      "orientation": "landscape",
      "dir": "/film/854",
      "width": 854,
      "height": 480,
      "totalBytes": 5304114,
      "avgBytes": 17680
    },
    {
      "id": "pv",
      "orientation": "portrait",
      "dir": "/film/810",
      "width": 810,
      "height": 1440,
      "totalBytes": 11558348,
      "avgBytes": 38528
    },
    {
      "id": "pvs",
      "orientation": "portrait",
      "dir": "/film/608",
      "width": 608,
      "height": 1080,
      "totalBytes": 7781758,
      "avgBytes": 25939
    }
  ],
  "cuts": [
    55,
    99,
    140,
    195,
    240
  ],
  "cutsPortrait": [
    54,
    98,
    139,
    195,
    239
  ],
  "heroFrames": [
    22,
    72,
    118,
    168,
    216,
    276
  ],
  "lqip": [
    "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoYAA4APu1iqk2ppaQiMAgBMB2JZQDG9CB4b5rau9jYNAPAAP6TftldYR85/8LczcGtY3KfjUZm0hzDHmKQMkZI1XXoVdQ6e3ydC9WdoAwfVtkdHmNwqJqNQgRcx2jwxwQEtnW1/saP+mGkibjq4evMjZnkU/QA",
    "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwDE2BUt3UBoXt1StYAAzgjvXHKaXzvI3GjwSJuL9y6rKrUnm/8qKWbrAS1Im5GATXq4P663J/iBxOxAMW3gvCmOndWtmAgkteLSOuic6tfDvvroAA==",
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoYAA4APu1iqk2ppaQiMAgBMB2JYwC7ACK5pYh5JX3umgusJYAA/tq/V7R4pdKUM5A7BTSVu791n6SM1FPapQlVEM/E9xBYCBSjMRvqcsAXExbsnJwiYfryYi8TgqaEz30qGc8nfn+ROCrif43HdRYuXbKhM91qiuh8AA==",
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwC+SCGZNsmLI/6HXEAA/ujUtsGJusPhd7Gtn82xOmSVn0dtHCF0q/z6w6B8xgkettrtJakHVfu4EWyXqwG0R4muhuUDmaMdBCUdfN8VjNooBhxiEAAA",
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQC7ACK4KDNflkCvAJ8gAP67apZVVNxK3W0EdUuqjuWeWI1sOZzOoWhIpZwslKDTjoGZWb37agb7XaUSEoIHMTqDuFKvvYYp9Z4Fg1IAsEfyFfjleZEhqS+LiAAA",
    "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdABhAX8w0WYgngG4AAP7BUNvj1rH7ImRheDWtigmhqLfweTlCMMtLqBTtcLbmW37vu9Lse+2sZHXtFLvxoKTSGG0TPzmTEHtip24HIcM/fVLorrt1UcCBATSQdHR5jLk0g8rZ3gfdaFQ0AA=="
  ],
  "lqipPortrait": [
    "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoOABgAPu1iqU2ppaOiMAgBMB2JYwCdAB0cOuww8hMmifxAAP2fUOcNDLJbp4MWzAZT0/2HcJtPQCddH9UPhO7h7yywqisc7QfOi7R1VJWAr1/6fxJMtYn8bDsOpnU76JGsYC6roOs8IgXzp4qutZtIOhuQpfctwwwL/i8Mk3CJyVMostF9cQ9gAAA=",
    "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQAwCdASoOABgAPu1iqU2ppaOiMAgBMB2JZwDE2Bt50bfjdR7uAaAA/s1XEjooq5n0FvWxqfEpuGtdR0+JTuJ/kJ767VgKv7kbxEl6Pfj2HOZ65dpt/s/5rmO4FMa5SfQGQDn79TsUGJtD/sEkh5EGvcfg3ifUrC88WNHuXQAAAA==",
    "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoOABgAPu1iqU2ppaOiMAgBMB2JZQC/OCPUQjb2i+2LulEBwoAA/s3bCjRsr7kg0aUdEyFsQkPLpvzrJ2akin+iJm4eWLiZi4hlWeI23BrnS8sq7PBN8+ZVWPs56WSSuYBRkA9IAXhe/SrTsDkuqiAeHeweAjqhPIv1zAPWYikFbERPvelVsaIyAAA=",
    "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoOABgAPu1iqU2ppaOiMAgBMB2JZQDDNYxY3k9P+TMoG6ljyJIkAP7kEcwXGHKxh+NmBgPegmmjWseYOmcRUtmdIEm+n9ACH3RqEmxPS+qE0DKjpQgc0dlrj9qUKpwLbIU1NsLQ3rzcte4EiWnlb7CIPWGVJ6nNpmthpeRZtA6T4XYmKIINhOJgAAA=",
    "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoOABgAPu1iqU2ppaOiMAgBMB2JYwAAVJe2VWMc/7+CIpiuAP7Rb8C1ftnHIfIP8OMYnmGjAEvLTEESGeKU/M1NUILFjSYljUWNOMmn2Wabqznk80zQKdAHs8DgAZkWSl4q09nLBoBK618p8z1+vSDBJA2+8Gxxh9E3/1oFkgS0AAAA",
    "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQAwCdASoOABgAPu1iqU2ppaOiMAgBMB2JZQAAYX1fUe6Jwqr6hAAA/tPr0aLJD97Ggw1GQ/TmfQn1CLZehUFnGmyoPguxWjY8kCqjdD2/eHpDGL05P8odwuux+aMFbTohZVEPB6zjl4huTaBFhFHFWBp2jjwL1E6hm6I65v8911/DC+RJUqVCAqpHYQgMJITulmAA"
  ]
} as const
